# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0002_auto_20160301_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='te',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
