# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 03:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0003_te_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='te',
            name='query',
            field=models.TextField(validators=[django.core.validators.RegexValidator('^[ACTGactg]*$', 'Must be a valid DNA sequence')]),
        ),
        migrations.AlterField(
            model_name='te',
            name='query_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
