# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0004_auto_20160301_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='te',
            name='query',
            field=models.TextField(),
        ),
    ]
