# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0005_auto_20160301_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='te',
            name='solution',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='te',
            name='threshold',
            field=models.IntegerField(default=0),
        ),
    ]
