# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0007_auto_20160301_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='te',
            name='reverse_query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
