# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tef', '0009_auto_20160324_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='te',
            name='distance',
            field=models.IntegerField(default=0),
        ),
    ]
